# Generated by Django 5.0.1 on 2024-01-21 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0002_aula_has_screen'),
        ('reservations', '0002_alter_reservation_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
                ('date_num', models.IntegerField(validators=[django.core.validators.MaxValueValidator(31)])),
                ('week_day', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('aula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_day', to='aulas.aula')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDayTimeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeblock', models.CharField(max_length=10)),
                ('calendar_day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationDayTimeIndex', to='calendar_day.calendarday')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationDayTimeIndex', to='reservations.reservation')),
            ],
        ),
    ]
