# Generated by Django 5.0.1 on 2024-01-22 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_aula_has_screen'),
        ('calendar_day', '0002_remove_reservationdaytimeindex_calendar_day_id_and_more'),
        ('reservations', '0002_alter_reservation_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarblock',
            name='aula_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_block', to='aulas.aula'),
        ),
        migrations.AlterField(
            model_name='calendarblock',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_block', related_query_name='calendar_block', to='reservations.reservation'),
        ),
    ]
