# Generated by Django 4.1.13 on 2024-03-08 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_day', '0003_alter_calendarblock_aula_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarblock',
            name='month',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
