# Generated by Django 4.1.13 on 2024-03-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_day', '0004_alter_calendarblock_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarblock',
            name='reservation_title',
            field=models.TextField(default='sin titulo'),
            preserve_default=False,
        ),
    ]
