# Generated by Django 3.2.25 on 2025-02-05 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_day', '0005_calendarblock_reservation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarblock',
            name='date_num',
        ),
        migrations.RemoveField(
            model_name='calendarblock',
            name='month',
        ),
        migrations.RemoveField(
            model_name='calendarblock',
            name='timeblock',
        ),
        migrations.RemoveField(
            model_name='calendarblock',
            name='week_day',
        ),
        migrations.AddField(
            model_name='calendarblock',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 5)),
        ),
        migrations.AddField(
            model_name='calendarblock',
            name='time_end',
            field=models.TimeField(default=datetime.time(23, 26, 29, 546493)),
        ),
        migrations.AddField(
            model_name='calendarblock',
            name='time_start',
            field=models.TimeField(default=datetime.time(23, 26, 29, 546481)),
        ),
    ]
