# Generated by Django 3.2.25 on 2025-02-05 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_day', '0006_auto_20250205_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarblock',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='calendarblock',
            name='time_start',
        ),
        migrations.AddField(
            model_name='calendarblock',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 35, 43, 926834)),
        ),
        migrations.AddField(
            model_name='calendarblock',
            name='start_time',
            field=models.TimeField(default=datetime.time(23, 35, 43, 926823)),
        ),
    ]
