services:
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    networks:
      - internal
      - external
    

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - internal

  frontend:
    build:
      context: ./AulasFront2
      dockerfile: ../dockerfile.front
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'

    depends_on:
      - api
    networks:
      - internal
      - external

volumes:
  postgres_data:
  static_volume:

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
