version: "3"

services:
 web:
   build: .
   command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
   volumes:
     - .:/code
     - db_data:/db.sqlite3
   ports:
     - "8080:8000"
   networks:
     - webinar-compose

volumes:
 db_data: {}

networks:
 webinar-compose: {}