# Generated by Django 5.0.1 on 2024-01-21 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0002_aula_has_screen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_category', models.CharField(choices=[('ateneo_servicio', 'ateneo_servicio'), ('carrera_especialista_servicio', 'carrera_especialista_servicio'), ('actividad_residentes', 'actividad_residentes'), ('UBA', 'UBA'), ('universidad_privada', 'universidad_privada'), ('tecnicaturas_hospital', 'tecnicaturas_hospital'), ('tecnicaturas_gob_ciudad', 'tecnicaturas_gob_ciudad'), ('actividad_especial', 'actividad_especial'), ('actividad_especial_direccion', 'actividad_especial_direccion')], default='actividad_especial_direccion', max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('frequency', models.CharField(choices=[('', ''), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='', max_length=255)),
                ('times', models.TextField(max_length=255)),
                ('aula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='aulas.aula')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
