# Generated by Django 5.0.1 on 2024-01-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='frequency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_category',
            field=models.CharField(max_length=255),
        ),
    ]
