# Generated by Django 4.1.13 on 2024-03-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.TextField(default='Reserva sin nombre', max_length=255),
            preserve_default=False,
        ),
    ]
