# Generated by Django 3.2.25 on 2025-02-05 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='times',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_category',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 26, 29, 545731)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_for',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=datetime.time(23, 26, 29, 545708)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 2, 5)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 2, 5)),
        ),
    ]
