# Generated by Django 3.2.25 on 2025-02-05 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20250205_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 35, 43, 926276)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=datetime.time(23, 35, 43, 926258)),
        ),
    ]
