# Generated by Django 5.0.1 on 2024-01-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('max_capacity', models.PositiveIntegerField()),
                ('has_negatoscope', models.BooleanField(default=False)),
            ],
        ),
    ]
