# Generated by Django 5.0.1 on 2024-01-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='has_screen',
            field=models.BooleanField(default=False),
        ),
    ]
