# Generated by Django 5.0.1 on 2024-02-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowed_emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=255),
            preserve_default=False,
        ),
    ]
